server:
  port: ${PORT:80}

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: info
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: error

aws:
  region: ${AWS_S3_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_S3_ACCESS_KEY:dummy}
    secret-key: ${AWS_S3_SECRET_KEY:dummy}
  s3:
    bucket: ${AWS_S3_BUCKET:dummy}

discodeit:
  storage:
    type: s3
