server:
  port: 8080

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  kafka:
    bootstrap-servers: broker:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: discodeit-${HOSTNAME}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: info
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: error

aws:
  region: ${AWS_S3_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_S3_ACCESS_KEY:dummy}
    secret-key: ${AWS_S3_SECRET_KEY:dummy}
  s3:
    bucket: ${AWS_S3_BUCKET:dummy}

discodeit:
  storage:
    type: s3
