events {}

http {

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  upstream backend {
      server backend-1:8080;
      server backend-2:8080;
      server backend-3:8080;
  }

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
      proxy_pass http://backend;

      add_header X-Upstream-Server $upstream_addr;
    }

    location /ws/ {
      proxy_pass http://backend;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";

      add_header X-Upstream-Server $upstream_addr;
    }

    location /assets/ {
      try_files $uri =404;
    }

    location / {
      try_files $uri /index.html;
    }
  }
}
