name: CD

on:
  push:
    branches: [ "release" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. AWS 자격 증명 설정
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # 2. Amazon ECR Public 로그인
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      # 2-1. 테스트 실행 및 Jacoco 리포트 생성
      - name: Run tests with Jacoco
        run: ./gradlew test jacocoTestReport

      # 2-2. Codecov로 리포트 업로드
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_URI }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:latest -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      # 4. AWS CLI 설정 재설정
      - name: Configure AWS credentials for ECS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5. 기존 서비스 중단
      - name: Stop existing ECS service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} \
                                 --service ${{ secrets.ECS_SERVICE }} \
                                 --desired-count 0

      # 6. 태스크 정의 업데이트 (기존 정의 기반 이미지 교체)
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: ${{ secrets.ECS_TASK_DEFINITION }}
          container-name: discodeit-app
          image: ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # 7. 새 태스크 정의로 서비스 재개
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          desired-count: 1
          wait-for-service-stability: false